version: '3.3'
services:
  webz-001:
    build:
      context: ./webz-001
      dockerfile: Dockerfile
    image: webz-001:latest
    container_name: webz-001
    hostname: webz-001
    networks:
      cluster_net:
        ipv4_address: 172.20.0.2
    ports:
      - "8081:80"
      - "3306"
    tty: true
    cap_add:
      - NET_ADMIN

  webz-002:
    build:
      context: ./webz-002
      dockerfile: Dockerfile
    image: webz-002:latest
    container_name: webz-002
    hostname: webz-002
    networks:
      cluster_net:
        ipv4_address: 172.20.0.3
    ports:
      - "8082:80"
      - "3306"
    tty: true
    cap_add:
      - NET_ADMIN

  webz-003:
    build:
      context: ./webz-003
      dockerfile: Dockerfile
    image: webz-003:latest
    container_name: webz-003
    hostname: webz-003
    networks:
      cluster_net:
        ipv4_address: 172.20.0.4
    ports:
      - "8083:80"
      - "3306"
    tty: true
    cap_add:
      - NET_ADMIN

  webz-004:
    image: jenkins/jenkins:lts
    container_name: webz-004
    hostname: webz-004
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./webz-004/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      cluster_net:
        ipv4_address: 172.20.0.6

networks:
  cluster_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

